---
# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

install:
  - . .envrc
  - go generate tools.go
  - go generate ./...

script:
  - go test ./...
  - go test ./... -count=100 -race

after_success:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux
  - osx

go:
  - "1.x"
  - "master"

matrix:
  allow_failures:
    - go: master

branches:
  only:
    - master

notifications:
  email:
    - adamluzsi@gmail.com
